[versions]
assertj="3.23.1"
autoValue="1.10"
checkstyle="10.4"
errorprone="2.16"
indra = "3.0.1"
junit="5.9.1"
ktlint="0.46.0"
pmd = "6.50.0"

[libraries]
# Shared
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
autoValue = { module = "com.google.auto.value:auto-value", version.ref = "autoValue" }
autoValue-annotations = { module = "com.google.auto.value:auto-value-annotations", version.ref = "autoValue" }
errorprone = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
errorprone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorprone" }
guava = "com.google.guava:guava:31.1-jre"
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
stylecheck = "ca.stellardrift:stylecheck:0.2.0"

# Kotlin
kotlin-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
kotlin-reflect = {module = "org.jetbrains.kotlin:kotlin-reflect"} # version from Kotlin BOM

# Core
checkerQual = "org.checkerframework:checker-qual:3.27.0"
geantyref = "io.leangen.geantyref:geantyref:1.3.13"

# DFU
dfu-v2 = "com.mojang:datafixerupper:2.0.24"
dfu-v3 = "com.mojang:datafixerupper:3.0.25"
dfu-v4 = "com.mojang:datafixerupper:4.0.26"
math = "org.spongepowered:math:2.0.1"
slf4j = "org.slf4j:slf4j-api:1.8.0-beta4" # Match version used in MC

# Guice
guice-compile = "com.google.inject:guice:4.1.0"
guice-runtime = "com.google.inject:guice:5.0.1"

# Formats
gson = "com.google.code.gson:gson:2.8.0" # Fixed version, to avoid using API not present in older MC
hocon = "com.typesafe:config:1.4.2"
jackson = "com.fasterxml.jackson.core:jackson-core:2.13.4"

# Tool
clikt = "com.github.ajalt:clikt:2.8.0"
jansi = "org.fusesource.jansi:jansi:2.4.0"

# Build
build-errorprone = "net.ltgt.gradle:gradle-errorprone-plugin:3.0.1"
build-forbiddenApis = "de.thetaphi:forbiddenapis:3.4"
build-goomph = "com.diffplug.gradle:goomph:3.40.0"
build-indra = { module = "net.kyori:indra-common", version.ref = "indra" }
build-indra-crossdoc = { module = "net.kyori:indra-crossdoc", version.ref = "indra" }
build-japicmp-plugin = "me.champeau.gradle:japicmp-gradle-plugin:0.4.1"
build-japicmp = { module = "com.github.siom79.japicmp:japicmp", version.require = "0.15.+" }
build-nullaway = "net.ltgt.gradle:gradle-nullaway-plugin:1.4.0"
build-spotless = "com.diffplug.spotless:spotless-plugin-gradle:6.11.0"

# For Renovate -- shouldn't need to use these directly
zPmd = { module = "net.sourceforge.pmd:pmd-java", version.ref = "pmd" }
zCheckstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }
zKtlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }

[plugins]
aggregateJavadoc = "io.freefair.aggregate-javadoc-jar:6.5.1"
detekt = "io.gitlab.arturbosch.detekt:1.21.0"
dokka = "org.jetbrains.dokka:1.7.20"
gitPublish = "org.ajoberstar.git-publish:3.0.1"
indra-common = { id = "net.kyori.indra", version.ref = "indra" }
indra-crossdoc = { id = "net.kyori.indra.crossdoc", version.ref = "indra" }
indra-sonatype = { id = "net.kyori.indra.publishing.sonatype", version.ref = "indra" }
indra-git = { id = "net.kyori.indra.git", version.ref = "indra" }
kotlin = "org.jetbrains.kotlin.jvm:1.7.20"
shadow = "com.github.johnrengelman.shadow:7.1.2"
