# Making changes? https://github.com/nektos/act may help you test locally

name: Configurate CI

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:
  release:
    types: [released]

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

env:
  JAVA_VERSION: 11

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"

    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      # Setup
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # checkout full history for site generation
          submodules: recursive
      - name: Set up committer info for patching
        run: |
          git config --global user.email "noreply@spongepowered.org"
          git config --global user.name "github-actions"
      - name: "Setup JDK ${{ env.JAVA_VERSION }}"
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "${{ env.JAVA_VERSION }}"
      - uses: gradle/wrapper-validation-action@v1

      # Actually build
      - name: Run Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: "${{ !(github.ref == 'refs/heads/master' || github.ref == 'refs/heads/3.x' || startsWith(github.ref, 'refs/heads/release/')) || github.event_name == 'pull_request' }}"
          arguments: build
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: "test-results-${{ runner.os }}"
          path: |
            build/reports/
            */build/reports/
            format/*/build/reports/
            extra/*/build/reports/

      # Then deploy, but only on the main branch
      - name: Determine status
        shell: bash
        run: |
          VERSION="$(./gradlew properties | awk '/^version:/ { print $2; }')"
          if [ "$(echo $VERSION | grep '\-SNAPSHOT')" ]; then
            echo "STATUS=snapshot" >> $GITHUB_ENV
          else
            echo "STATUS=release" >> $GITHUB_ENV
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Publish with Gradle
        if: "${{ runner.os == 'Linux' && ((env.STATUS == 'release' && github.event_name == 'release') || (env.STATUS != 'release' && github.event_name != 'release' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/3.x' || startsWith(github.ref, 'refs/heads/release/')))) }}"
        run: |
          ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish configurate-tool as release artifact
        if: "${{ runner.os == 'Linux' && env.STATUS == 'release' && github.event_name == 'release' }}"
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tool/build/distributions/tool-${{ env.VERSION }}.tar.gz
            tool/build/distributions/tool-${{ env.VERSION }}.zip
